nelmio_api_doc:
    documentation:
        info:
            title: Projet 7
            description: Documentation d'un web service exposant une API
            version: 1.0.0


        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]

    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc